%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.6

-ifndef(emqttd_gpb).
-define(emqttd_gpb, true).

-define(emqttd_gpb_gpb_version, "3.26.6").

-ifndef('DISCONNECTEDMESSAGE_PB_H').
-define('DISCONNECTEDMESSAGE_PB_H', true).
-record('DisconnectedMessage',
{reason                         % = 1, string (optional)
}).
-endif.

-ifndef('CONNECTEDMESSAGE_PB_H').
-define('CONNECTEDMESSAGE_PB_H', true).
-record('ConnectedMessage',
{ip_address,                    % = 1, string (optional)
  conn_ack,                      % = 2, {enum,'ConnectedMessage.ConnAck'} (optional)
  session,                       % = 3, bool (optional)
  protocol_version               % = 4, int32 (optional)
}).
-endif.

-ifndef('EMQTTDPRESENCE_PB_H').
-define('EMQTTDPRESENCE_PB_H', true).
-record('EmqttdPresence',
{username,                      % = 1, string (optional)
  client_id,                     % = 2, string (optional)
  time,                          % = 3, int64 (optional)
  presence                       % oneof
}).
-endif.

-ifndef('EMQTTDMESSAGE_PB_H').
-define('EMQTTDMESSAGE_PB_H', true).
-record('EmqttdMessage',
{username,                      % = 1, string (optional)
  client_id,                     % = 2, string (optional)
  topic,                         % = 3, string (optional)
  qos,                           % = 4, int32 (optional)
  retain,                        % = 5, bool (optional)
  dup,                           % = 6, bool (optional)
  id,                            % = 7, int32 (optional)
  payload                        % = 8, bytes (optional)
}).
-endif.

-endif.
